version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    restart: on-failure
    platform: linux/amd64
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6:
